✨ Reward Increase
Hona/BlazorClickerGame pull request #2
Opened 2024-03-01 05:43 UTC by tkapa

# Pain
At the moment, users only gain 1 `currency` per kill.

# What's changed?

We now increase the currency by `1 + (EnemiesDefeated / 10)` to passively increase how much the player gains over the course of play.

Also fixes a bug where an enemy will only die when `< 0` HP.

2024-03-04 23:38 UTC, Hona requested changes

2024-03-04 23:38 UTC, Hona commented on BlazorGameSpike/BlazorGameSpike.Client/State/GameState.cs
> +            AddCurrency(1 + (EnemiesDefeated / 10));
Lets make it EnemiesDefeated / 100

2024-03-15 05:48 UTC, tkapa commented on BlazorGameSpike/BlazorGameSpike.Client/State/GameState.cs
> +            AddCurrency(1 + (EnemiesDefeated / 10));
Done

2024-03-15 05:48 UTC, Hona approved these changes
Great work!

2024-03-15 05:48 UTC, merged